"use client";
import { useState } from "react";
import type { Battlecard, Preset } from "@/lib/types";
const presets: Array<[Preset, string]> = [["general", "通用"], ["ecommerce", "电商"], ["foreign_trade", "外贸"], ["ai", "AI"], ["manufacturing", "制造业"]];
export default function Home() {
 const [targetUrl,setTargetUrl]=useState("https://example.com"),[preset,setPreset]=useState<Preset>("general"),[productName,setProductName]=useState("你的产品"),[value,setValue]=useState("把公开信息整理成销售前可直接使用的行动建议"),[card,setCard]=useState<Battlecard>(),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError("");const response=await fetch("/api/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetUrl,preset,sellerProfile:{productName,valueProposition:value,targetCustomer:"需要拓展客户的销售团队",customerProblems:["售前准备信息分散"],proofPoints:["每条事实可追溯来源"],callToAction:"安排一次 20 分钟演示"}})});const data=await response.json();setLoading(false);if(!response.ok){setError(data.error??"生成失败");return;}setCard(data);}
 return <main className="shell"><header><p className="kicker">PRE-CALL RESEARCH / V0.1</p><h1>售前销售情报<br/>作战卡</h1><p className="lede">公开网页证据 → 销售推理 → 下一次拜访的具体动作。</p></header><form onSubmit={submit} className="intake"><label>目标公司网址<input value={targetUrl} onChange={e=>setTargetUrl(e.target.value)} required/></label><label>行业预设<select value={preset} onChange={e=>setPreset(e.target.value as Preset)}>{presets.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>你的产品<input value={productName} onChange={e=>setProductName(e.target.value)} required/></label><label className="wide">一句价值主张<input value={value} onChange={e=>setValue(e.target.value)} required/></label><button disabled={loading}>{loading?"正在生成…":"生成作战卡"}</button></form>{error&&<p className="error">{error}</p>}{card&&<section className="card"><aside><b>证据线</b><span>01</span><span>02</span></aside><div><p className="kicker">60 SECOND OVERVIEW</p><h2>{card.overview.text}</h2><div className="grid"><Block title="观察到的信号" items={card.signals.map(i=>i.text)}/><Block title="待验证的痛点" items={card.painHypotheses.map(i=>i.text)}/><Block title="可这样切入" items={card.productMappings.map(i=>i.expectedValue)}/><Block title="开场白" items={[card.opening.text]}/></div><h3>五个发现型问题</h3><ol>{card.questions.map(i=><li key={i.question}>{i.question}</li>)}</ol><h3>来源</h3>{card.sources.map((s,i)=><a className="source" key={s.id} href={s.url} target="_blank" rel="noreferrer">[{String(i+1).padStart(2,"0")}] {s.title}</a>)}{card.warnings.map(w=><p className="warning" key={w}>{w}</p>)}</div></section>}</main>;
}
function Block({title,items}:{title:string;items:string[]}){return <section><h3>{title}</h3>{items.map(item=><p key={item}>{item}</p>)}</section>;}
